I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/script.rpy", line 11, in script call
    call meetings
  File "game/scripts/chapters/Chapter 2/meetings.rpy", line 30, in script call
    call theOtherFamilies
  File "game/scripts/chapters/Chapter 2/the other families.rpy", line 58, in script call
    call visitingTheBloodrunners
  File "game/scripts/chapters/Chapter 2/the other families.rpy", line 541, in script
    e "I'm doing great! I'm a [ally.career]! Lots of things to learn."
KeyError: u'ally'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/script.rpy", line 11, in script call
    call meetings
  File "game/scripts/chapters/Chapter 2/meetings.rpy", line 30, in script call
    call theOtherFamilies
  File "game/scripts/chapters/Chapter 2/the other families.rpy", line 58, in script call
    call visitingTheBloodrunners
  File "game/scripts/chapters/Chapter 2/the other families.rpy", line 541, in script
    e "I'm doing great! I'm a [ally.career]! Lots of things to learn."
  File "D:\Users\Pyro\Dropbox\Programming\Ren'py\renpy-6.18.3-sdk\renpy\ast.py", line 593, in execute
    renpy.exports.say(who, what, interact=self.interact)
  File "D:\Users\Pyro\Dropbox\Programming\Ren'py\renpy-6.18.3-sdk\renpy\exports.py", line 999, in say
    who(what, interact=interact)
  File "D:\Users\Pyro\Dropbox\Programming\Ren'py\renpy-6.18.3-sdk\renpy\character.py", line 817, in __call__
    what = what_pattern.replace("[what]", sub(what, translate=translate))
  File "D:\Users\Pyro\Dropbox\Programming\Ren'py\renpy-6.18.3-sdk\renpy\character.py", line 799, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "D:\Users\Pyro\Dropbox\Programming\Ren'py\renpy-6.18.3-sdk\renpy\substitutions.py", line 229, in substitute
    s = formatter.vformat(s, (), kwargs)
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 549, in vformat
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 571, in _vformat
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 632, in get_field
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 591, in get_value
KeyError: u'ally'

Windows-7-6.1.7601-SP1
Ren'Py 6.18.3.761
Riverwood 0.0
